name: Pytest

on: [push]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        pip install pytest
        pip install -r ./tests/requirements.txt
    - name: Test OlliePy
      run: |
        poetry run pytest --junit-xml=./tests/tests-report/reprot.xml tests

