name: Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Python Pytest GitHub Action
      uses: fylein/python-pytest-github-action@v2
      with:
        args: pip3 install tests/requirements.txt && pytest tests

