name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-18.04
    name: Generate Test Reports
    env:
      RESULTS_PATH: alternate-location
    steps:
      - name: Generate Report
        id: xunit-viewer
        uses: AutoModality/action-xunit-viewer@v1
        with:
          results: ${{ env.TEST_RESULTS_PATH }}
      - name: The generated report
        run: echo "The report is ${{ steps.xunit-viewer.outputs.report-file }}"    
      - name: Attach the report
        uses: actions/upload-artifact@v1
        with:
          name: alternate-results-path-reports
          path: ${{ env.TEST_RESULTS_PATH }}
